---
title: Wild About Pilates
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@wildaboutpilates.co.uk
tel: '07378 166524'
tel_int: "+44-7378-166524"
description: Description
url: https://www.wildaboutpilates.co.uk
markdown: kramdown
permalink: pretty
sass:
  style: compressed
